# Bun Configuration File

# Test Configuration
[test]

# Enable coverage reporting
coverage = true

# Coverage output directories and formats
coverageDirectory = "coverage"
coverageReporter = ["text", "lcov"]

# Test file patterns
root = "./packages"
# Match test files in tests directories
patterns = ["**/tests/**/*.test.ts", "**/tests/**/*.spec.ts"]

# Timeout for tests (ms)
timeout = 5000

# Path Aliases (matching tsconfig paths)
[test.alias]
"@checklist/core" = "./packages/core/src"
"@checklist/cli" = "./packages/cli/src"  
"@checklist/tui" = "./packages/tui/src"
"@checklist/shared" = "./packages/shared/src"

# Coverage thresholds
coverageThreshold = { lines = 80, functions = 80, branches = 80, statements = 80 }

# Files to exclude from coverage
coverageExclude = [
  "**/node_modules/**",
  "dist/**",
  "**/dist/**",
  "*.config.ts",
  "*.config.js",
  "*.config.mjs",
  "*.config.cjs",
  "**/*.config.ts",
  "**/*.config.js",
  "**/*.config.mjs",
  "**/*.config.cjs",
  "**/*.mock.ts",
  "**/*.test.ts",
  "**/*.spec.ts",
  "**/*.bench.ts",
  "**/tests/**/*",
  "**/test-utils/**/*",
  "**/mocks/**/*",
  "**/examples/**",
  "**/scripts/**",
  ".prettierrc.js",
  "eslint.config.js",
  "performance.config.ts"
]

# Files to include in coverage - be explicit about src only, excluding test files
coverageInclude = [
  "packages/core/src/**/*.ts",
  "packages/cli/src/**/*.ts",
  "packages/tui/src/**/*.ts",
  "packages/shared/src/**/*.ts",
  "!packages/**/*.mock.ts",
  "!packages/**/*.test.ts",
  "!packages/**/*.spec.ts",
  "!packages/**/*.bench.ts",
  "!packages/**/*.config.ts",
  "!packages/**/tests/**",
  "!packages/**/test-utils/**",
  "!packages/**/mocks/**"
]

# Skip coverage for compiled files
coverageSkipFullyInstrumented = true

# Development Configuration
[dev]
# Watch for file changes
watch = true

# Install Configuration
[install]
# Package manager settings
lockfile = true
optional = true
dev = true
peer = true

# Auto-install missing packages
auto = false

# Cache Configuration
[install.cache]
# Cache directory
dir = "~/.bun/cache"

# Runtime Configuration
[run]
# Silent mode for scripts
silent = false

# JSX Configuration (if needed for TUI)
[jsx]
# JSX runtime
runtime = "automatic"

# Macro Configuration
[macro]
# Enable macros
enabled = false