name: Performance Benchmarks

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Run benchmarks daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUN_VERSION: 1.2
  NODE_TLS_REJECT_UNAUTHORIZED: 1

jobs:
  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Create Performance Directory
        run: mkdir -p .performance/baselines

      - name: Download Previous Baselines
        uses: actions/download-artifact@v4
        with:
          name: performance-baselines
          path: .performance/baselines
        continue-on-error: true

      - name: Run Startup Benchmarks
        run: bun run bench:startup
        continue-on-error: true

      - name: Run Memory Benchmarks
        run: bun run bench:memory
        continue-on-error: true

      - name: Run Operation Benchmarks
        run: bun run bench:operations
        continue-on-error: true

      - name: Compare Results
        run: bun run bench:compare
        continue-on-error: true

      - name: Validate Performance Budget
        run: bun run bench:assert

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: benchmark-results
          path: .performance/
          retention-days: 30

      - name: Upload Performance Baselines
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: performance-baselines
          path: .performance/baselines/
          retention-days: 90

      - name: Comment PR with Results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = '.performance/comparison-report.md';
            if (fs.existsSync(path)) {
              const report = fs.readFileSync(path, 'utf8');
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 📊 Performance Benchmark Results\n\n${report}`
              });
            }