name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Build all platforms
        run: |
          # Build for Linux
          bun build --compile --target=bun-linux-x64 --outfile=dist/checklist-linux
          
          # Build for macOS x64
          bun build --compile --target=bun-darwin-x64 --outfile=dist/checklist-macos-x64
          
          # Build for macOS ARM64
          bun build --compile --target=bun-darwin-arm64 --outfile=dist/checklist-macos-arm64
          
          # Build for Windows
          bun build --compile --target=bun-windows-x64 --outfile=dist/checklist-windows.exe

      - name: Validate binary sizes
        run: |
          for file in dist/*; do
            size=$(stat -c%s "$file" 2>/dev/null || stat -f%z "$file" 2>/dev/null)
            mb=$((size / 1048576))
            if [ $mb -gt 20 ]; then
              echo "ERROR: $file is ${mb}MB, exceeds 20MB limit"
              exit 1
            fi
            echo "$file: ${mb}MB ✓"
          done

      - name: Generate changelog
        id: changelog
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          git log --pretty=format:"- %s (%h)" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## What's Changed
            ${{ steps.changelog.outputs.CHANGELOG }}
            
            ## Downloads
            - **Linux**: `checklist-linux`
            - **macOS Intel**: `checklist-macos-x64`
            - **macOS Apple Silicon**: `checklist-macos-arm64`
            - **Windows**: `checklist-windows.exe`
          files: |
            dist/checklist-linux
            dist/checklist-macos-x64
            dist/checklist-macos-arm64
            dist/checklist-windows.exe
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-beta') || contains(github.ref, '-alpha') }}

      - name: Prepare npm package
        if: ${{ !contains(github.ref, '-rc') && !contains(github.ref, '-beta') && !contains(github.ref, '-alpha') }}
        run: |
          # Update package.json version
          VERSION=${GITHUB_REF#refs/tags/v}
          npm version $VERSION --no-git-tag-version
          
          # Dry run first to validate
          npm publish --dry-run

      # Uncomment when NPM_TOKEN is configured
      # - name: Publish to npm
      #   if: ${{ !contains(github.ref, '-rc') && !contains(github.ref, '-beta') && !contains(github.ref, '-alpha') }}
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npm publish